version: '3.8'

services:
  # TypeScript + Express アプリ
  typescript-app:
    build: .
    container_name: ts-learning
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./nodemon.json:/app/nodemon.json
      - ./package.json:/app/package.json
      - ./.dockerignore:/app/.dockerignore
    environment:
      # PostgreSQL
      - PGHOST=postgres
      - PGUSER=devuser
      - PGPASSWORD=devpass
      - PGDATABASE=devdb
      - PGPORT=5432
      # MySQL
      - MYSQL_HOST=mysql
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
      - MYSQL_DATABASE=devdb
      - MYSQL_PORT=3306
      # MariaDB
      - MARIADB_HOST=mariadb
      - MARIADB_USER=devuser
      - MARIADB_PASSWORD=devpass
      - MARIADB_DATABASE=devdb
      - MARIADB_PORT=3306
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - mysql
      - mariadb
      - redis
    networks:
      - db-net
    command: ["nodemon"] # ホットリロード開始 :contentReference[oaicite:10]{index=10}

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d # 初期化スクリプト :contentReference[oaicite:11]{index=11}
    ports:
      - "5432:5432"
    networks:
      - db-net

  # MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d # 初期化スクリプト :contentReference[oaicite:12]{index=12}
    ports:
      - "3306:3306"
    networks:
      - db-net

  # MariaDB
  mariadb:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: devdb
      MARIADB_USER: devuser
      MARIADB_PASSWORD: devpass
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d # 初期化スクリプト :contentReference[oaicite:13]{index=13}
    ports:
      - "3307:3306"
    networks:
      - db-net

  # Redis (公式イメージ + 設定ファイル読み込み) :contentReference[oaicite:14]{index=14}
  redis:
    image: redis:latest
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"] # 設定適用 :contentReference[oaicite:15]{index=15}
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - db-net

  # Adminer (DB GUI)
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - db-net

  # Nginx (リバースプロキシ) :contentReference[oaicite:16]{index=16}
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - typescript-app
      - adminer
    networks:
      - db-net

volumes:
  postgres-data:
  mysql-data:
  mariadb-data:
  redis-data:

networks:
  db-net:
    driver: bridge
